# Generated by Django 4.2.4 on 2024-05-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
