# Generated by Django 4.2.4 on 2024-05-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_deposit_max_limit_alter_deposit_mtrt_int_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='max_limit',
        ),
    ]
